name: CI/CD Pipeline ğŸš€

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Hub Login ğŸ”
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image ğŸ³
        run: |
          docker build --platform linux/amd64 \
          -t ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest ./backend

      - name: Build Frontend Image ğŸ³
        run: |
          docker build --platform linux/amd64 \
          -t ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest ./frontend

      - name: Push Images ğŸš€
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest

      - name: Deploy to EC2 â˜ï¸ğŸ”¥
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull sandy2003/dd-backend:latest
            docker pull sandy2003/dd-frontend:latest
            docker-compose down
            docker-compose up -d
